# Generated by Django 4.2.7 on 2023-11-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_alter_institution_district_alter_institution_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_account',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_branch',
            field=models.CharField(default='branch', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_holder',
            field=models.CharField(default='holder', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='student_ifsc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=50),
        ),
    ]
